- name: Install Motion Dependencies
  apt:
    name: ffmpeg, libmariadb3, libpq5, libmicrohttpd12
- name: Get Motion
  get_url: 
    url: https://github.com/Motion-Project/motion/releases/download/release-4.2.2/pi_buster_motion_4.2.2-1_armhf.deb
    dest: /home/pi/pi_buster_motion.armhf.deb
- name: Install Motion Package
  apt: 
    deb: /home/pi/pi_buster_motion.armhf.deb
- name: Install MotionEye Dependencies
  apt:
    name: python3-pip, python-pip, python-dev, libssl-dev, libcurl4-openssl-dev, libjpeg-dev, libz-dev
- name: Install MotionEye
  pip:
    name: motioneye

- name: Prepare Configuration for MotionEye
  file:
    path: /etc/motioneye
    state: directory

- name: Copy Configuration
  command:
    cmd: cp /usr/local/share/motioneye/extra/motioneye.conf.sample /etc/motioneye/motioneye.conf
    creates: /etc/motioneye/motioneye.conf

- name: Prepare Media Directory
  file:
    path: /var/lib/motioneye
    state: directory

- name: Add init script
  command:
    cmd: cp /usr/local/share/motioneye/extra/motioneye.systemd-unit-local /etc/systemd/system/motioneye.service
    creates: /etc/systemd/system/motioneye.service

- name: Start / Init MotionEye Daemon
  systemd:
    name: motioneye
    state: started
    enabled: yes
    daemon_reload: yes
