---
galaxy_info:
# TODO: Replace with usage by ansible-galaxy backed role
# : https://github.com/humio/ansible-java
  author: Alex Lapinski
  description: Install java runtime (zulu) for dependant apps.
  license: MIT
  min_ansible_version: 1.2

  platforms:
  - name: Rasbpian

  galaxy_tags: []
  
dependencies: []