name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint ansible files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ansible-lint
        uses: ansible/ansible-lint-action@v4.1.0.post0

  test:
  #  name: Run Ansible tests with moecule
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #      
  #    - name: Run Molecule
  #      uses: robertdebock/molecule-action@1.2.8
  #      with:
  #        image: ubuntu-latest
